dist: trusty
#
#language: java

jdk:
  - oraclejdk11

# https://docs.travis-ci.com/user/sonarcloud/

addons:
  sonarcloud:
    organization: "speech4j"
    token:
      secure: "KoEoC5kRdOwrvsaO3DvRkSUrn3Fux6toyVA4gmMjQt0PaSNux1u9a13U2i1GjzaeSG8+y6Owx3C270ajxcp1lxK1+yfgHOeR+pVBjFaZrkxnG8JyXPJzJtoA+DhDYPyIucN4OKwAYCJykNqTeY3vz1oVqetzoxAgCu82oFqJ6TZ2QAn0Y6ahfuF3XV7VD7WehH6YdKFUBDb9lxWsQksDMzxFHzkpynkOhcWtDLpmVLM2bPfGWDI5NrGr/hlOkbSQnG1l82s4X0DmurjVUcfcl06PQZilnMHpnv7L305PHdu2s81GT9ULfAwQIMPMkBQDRL6XGoKZT49MgsRt6MK4VCm/oJ0xzSoLIxE+iYlA9VA/Rp5vR8KmqkJrlqzzclB3wy/1bXNEMh47i7xRguxAiV1lHkY51Z1WTYyFTldV7vKSXzyKGsEgB+VTFPpnHDgwK60tllHTaVfEYki92jBEF939iaw79RLb0ZHGyQvBbr+j5Y7Ma3zH5c91PyWqsUz825UkOdF7RgyhnRYQLo672JYvSq5GnNl7xsaiHYSlyVCshMNORrpEXU+VRUiUkOdHXojT19SoPqXMDyO4tYzvAKrYLJnBVb85jyTI67JVW//bUJAyJrdT9DEBm8M8UdFaWuJ+DzHy/u9zsV8elikB0n/1LHyzyzMnXW4IiSeAciA="

script:
  - ./gradlew sonarqube
  - ./gradlew jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'

# https://adamweidner.com/posts/sonar-with-gradle-submodules/
# https://sonarcloud.io/dashboard?id=speech4j_speech4j
# https://github.com/SonarSource/sq-com_example_java-gradle-travis/blob/master/.travis.yml
# https://testdriven.io/blog/getting-telegram-notifications-from-travis-ci/
# https://docs.travis-ci.com/user/notifications/#configuring-slack-notifications
# https://medium.com/@proustibat/using-sonarcloud-with-travis-ci-to-measure-and-continuously-improve-code-quality-5ea7fb5a587b
# https://asus-aics.github.io/DeveloperGuide/pages/020_sonar_cloud/